language: python # language expected
python: # python version
  - "3.9"
services: # services travis needs to use
  - docker  
before_script: pip install docker-compose
script:
  - docker-compose run  app sh -c "python manage.py test && python manage.py test && flake8"
